apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-cnf
  name: worker-cnf
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker-cnf
      - worker
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-cnf: ""
