apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-cnf
  name: blacklist-ipi
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:,
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/manifests/coredns.yaml
      - contents:
          source: data:,
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/manifests/keepalived.yaml
      - contents:
          source: data:,
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/manifests/mdns-publisher.yaml
      - contents:
          source: data:;base64,W21haW5dCnJjLW1hbmFnZXI9ZmlsZQpbY29ubmVjdGlvbl0KaXB2Ni5kaGNwLWR1aWQ9bGwKaXB2Ni5kaGNwLWlhaWQ9bWFjCltrZXlmaWxlXQp1bm1hbmFnZWQtZGV2aWNlcz1pbnRlcmZhY2UtbmFtZTplbnAzczBmMQo=
        filesystem: root
        mode: 420
        overwrite: true
        path: /etc/NetworkManager/conf.d/99-onprem-cluster.conf
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
          Wants=network-online.target
          After=network-online.target ignition-firstboot-complete.service
          Before=kubelet.service crio.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c "if [[ $(hostname) == *localhost* ]];then REVERSE=$(dig -x $(hostname -I | cut -f1 -d\ ) +short) ; HOSTNAME=${REVERSE::-1}; echo $HOSTNAME > /etc/hostname ; nmcli general hostname $HOSTNAME ; systemctl restart systemd-hostnamed;else echo hostname is correct;fi"
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: nodeip-configuration.service
