apiVersion: v1
kind: Namespace
metadata:
  name: autorules
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autorules
  namespace: autorules
data:
  rules1.properties: |
    name: .*spoke2.*
    labels:
    - node-role.kubernetes.io/worker-cnf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autorules-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: autorules
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoruler
  namespace: autorules
  labels:
    app: autoruler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoruler
  template:
    metadata:
      labels:
        app: autoruler
    spec:
      containers:
      - name: autosigner
        image: bm-cluster-1-hyper.e2e.bos.redhat.com:5000/karmab/autosigner:latest
      - name: autolabeller
        image: bm-cluster-1-hyper.e2e.bos.redhat.com:5000/karmab/autolabeller:latest
